# Generated by Django 5.1.15 on 2026-09-24 23:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_store_allows_delivery_store_allows_pickup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(help_text='Ex: Centro, Zona Sul, Bairros Próximos', max_length=100, verbose_name='Nome da Região / Zona')),
                ('neighborhoods', models.TextField(blank=True, help_text='Nomes dos bairros abrangidos por esta taxa, separados por vírgula.', verbose_name='Bairros / Regiões Atendidas')),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor do frete para esta região.', max_digits=10, verbose_name='Taxa de Entrega (R$)')),
                ('estimated_time_min', models.PositiveIntegerField(default=30, verbose_name='Tempo Estimado Mínimo (min)')),
                ('estimated_time_max', models.PositiveIntegerField(default=60, verbose_name='Tempo Estimado Máximo (min)')),
                ('is_active', models.BooleanField(default=True, help_text='Se desativada, a loja não fará entregas para esta região temporariamente.', verbose_name='Zona Ativa')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Região de Entrega',
                'verbose_name_plural': 'Regiões de Entrega',
                'ordering': ['fee', 'name'],
            },
        ),
    ]
