# Generated by Django 5.1.15 on 2026-09-24 23:38

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_optiongroup_store'),
        ('customers', '0001_initial'),
        ('stores', '0002_store_allows_delivery_store_allows_pickup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='ID Público')),
                ('order_number', models.PositiveIntegerField(db_index=True, help_text='Identificador amigável sequencial por loja (ex: 1001, 1002).', verbose_name='Número do Pedido')),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('ACEITO', 'Aceito'), ('EM_PREPARACAO', 'Em Preparação'), ('PRONTO', 'Pronto para Retirada / Envio'), ('SAIU_PARA_ENTREGA', 'Saiu para Entrega'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], db_index=True, default='NOVO', max_length=25, verbose_name='Status')),
                ('delivery_type', models.CharField(choices=[('DELIVERY', 'Entrega'), ('PICKUP', 'Retirada na Loja')], default='DELIVERY', max_length=15, verbose_name='Modalidade')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal dos Itens (R$)')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Taxa de Entrega (R$)')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total do Pedido (R$)')),
                ('payment_method', models.CharField(choices=[('MONEY', 'Dinheiro'), ('PIX', 'Pix'), ('DEBIT_CARD', 'Cartão de Débito (na entrega)'), ('CREDIT_CARD', 'Cartão de Crédito (na entrega)'), ('MEAL_VOUCHER', 'Vale-Refeição'), ('OTHER', 'Outros')], default='PIX', max_length=20, verbose_name='Forma de Pagamento')),
                ('change_for', models.DecimalField(blank=True, decimal_places=2, help_text='Caso o cliente pague em dinheiro e necessite de troco.', max_digits=10, null=True, verbose_name='Troco para (R$)')),
                ('street', models.CharField(blank=True, max_length=150, verbose_name='Rua / Logradouro')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='Estado (UF)')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('reference', models.CharField(blank=True, max_length=150, verbose_name='Ponto de Referência')),
                ('notes', models.TextField(blank=True, verbose_name='Observações Gerais do Pedido')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer', verbose_name='Cliente')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
                'unique_together': {('store', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('product_name', models.CharField(max_length=150, verbose_name='Nome do Produto')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário (R$)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal do Item (R$)')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total com Adicionais (R$)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações do Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='Produto Original')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Opção')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preço Adicional (R$)')),
                ('group_name', models.CharField(blank=True, max_length=100, verbose_name='Grupo de Opção')),
                ('option_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.optionitem', verbose_name='Opção Original')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='orders.orderitem', verbose_name='Item do Pedido')),
            ],
            options={
                'verbose_name': 'Opção do Item de Pedido',
                'verbose_name_plural': 'Opções dos Itens de Pedido',
                'ordering': ['id'],
            },
        ),
    ]
