# Generated by Django 5.1.15 on 2026-09-25 15:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_accepted_at_order_preparing_at_order_ready_at'),
        ('stores', '0004_store_fixed_delivery_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=30, verbose_name='Código do Cupom'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor de desconto concedido por cupom ou promoção.', max_digits=10, verbose_name='Desconto (R$)'),
        ),
        migrations.AddField(
            model_name='order',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='Usuário lojista responsável por registrar a venda no PDV.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_orders', to=settings.AUTH_USER_MODEL, verbose_name='Operador do PDV'),
        ),
        migrations.AddField(
            model_name='order',
            name='origin',
            field=models.CharField(choices=[('ONLINE', 'Online (Cardápio)'), ('PDV', 'PDV (Balcão)')], db_index=True, default='ONLINE', help_text='Identifica se a venda foi originada pelo Cardápio Online ou pelo PDV.', max_length=10, verbose_name='Origem do Pedido'),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_returned',
            field=models.BooleanField(default=False, help_text='Indica se o estoque já foi devolvido após cancelamento do pedido.', verbose_name='Estoque Estornado'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('code', models.CharField(help_text='Código digitado pelo cliente ou operador (ex: BEMVINDO10).', max_length=30, verbose_name='Código do Cupom')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Porcentagem (%)'), ('FIXED', 'Valor Fixo (R$)')], default='PERCENTAGE', max_length=15, verbose_name='Tipo de Desconto')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentual (ex: 10 para 10%) ou valor fixo em R$ (ex: 15.00).', max_digits=10, verbose_name='Valor do Desconto')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal mínimo de mercadorias para liberar o cupom.', max_digits=10, verbose_name='Valor Mínimo do Pedido (R$)')),
                ('apply_to_delivery', models.BooleanField(default=False, help_text='Se marcado, o desconto pode incidir sobre o total com frete. Se desmarcado, incide apenas nas mercadorias.', verbose_name='Desconto no Total Geral (inclui frete)')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Deixe em branco para usos ilimitados.', null=True, verbose_name='Limite Máximo de Usos')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Quantidade de Usos')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Válido a partir de')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Válido até')),
                ('is_public', models.BooleanField(default=False, help_text='Se ativo, exibe o cupom publicamente incentivando o cliente a atingir o valor mínimo.', verbose_name='Destacar no Cardápio / Checkout')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Cupom de Desconto',
                'verbose_name_plural': 'Cupons de Desconto',
                'ordering': ['-created_at'],
                'unique_together': {('store', 'code')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.coupon', verbose_name='Cupom Aplicado'),
        ),
    ]
