# Generated by Django 5.1.15 on 2026-09-27 20:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_coupon_code_order_discount_order_operator_and_more'),
        ('stores', '0004_store_fixed_delivery_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('DELIVERY', 'Entrega'), ('PICKUP', 'Retirada na Loja'), ('DINE_IN', 'Consumo no Local / Mesa')], default='DELIVERY', max_length=15, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='order',
            name='origin',
            field=models.CharField(choices=[('ONLINE', 'Online (Cardápio)'), ('PDV', 'PDV (Balcão)'), ('TABLE', 'Mesa (QR Code)')], db_index=True, default='ONLINE', help_text='Identifica se a venda foi originada pelo Cardápio Online, PDV ou Mesa QR.', max_length=10, verbose_name='Origem do Pedido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NOVO', 'Novo'), ('ACEITO', 'Aceito'), ('EM_PREPARACAO', 'Em Preparação'), ('PRONTO', 'Pronto para Retirada / Envio'), ('SAIU_PARA_ENTREGA', 'Saiu para Entrega / Na Mesa'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], db_index=True, default='NOVO', max_length=25, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('number', models.CharField(db_index=True, help_text='Ex: 01, 12, Varanda 3, Deck 02.', max_length=20, verbose_name='Número da Mesa')),
                ('name', models.CharField(blank=True, help_text='Ex: Salão Principal, Vista Mar, VIP.', max_length=100, verbose_name='Identificação / Nome Opcional')),
                ('qr_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Token criptográfico não sequencial para o QR Code da mesa.', unique=True, verbose_name='Token Seguro do QR Code')),
                ('is_active', models.BooleanField(default=True, help_text='Se desativada, não aceita pedidos nem novas sessões.', verbose_name='Ativa')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['number'],
                'unique_together': {('store', 'number')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, help_text='Mesa vinculada caso a venda tenha sido originada por QR Code ou consumida no local.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.table', verbose_name='Mesa Física'),
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='ID Público')),
                ('session_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de Validação da Sessão')),
                ('status', models.CharField(choices=[('OPEN', 'Em Consumo (Aberta)'), ('WAITING_PAY', 'Aguardando Pagamento (Pediu a Conta)'), ('CLOSED', 'Encerrada / Paga'), ('CANCELLED', 'Cancelada')], db_index=True, default='OPEN', max_length=20, verbose_name='Status da Sessão')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Aberta em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Encerrada em')),
                ('payment_method', models.CharField(blank=True, max_length=20, verbose_name='Forma de Pagamento')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Desconto (R$)')),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Pago (R$)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações da Mesa / Comanda')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_table_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Operador Responsável pelo Fechamento')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Loja')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='orders.table', verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Sessão de Mesa / Comanda',
                'verbose_name_plural': 'Sessões de Mesas / Comandas',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table_session',
            field=models.ForeignKey(blank=True, help_text='Comanda agregada contínua de consumo da mesa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.tablesession', verbose_name='Sessão da Mesa / Comanda'),
        ),
        migrations.AddConstraint(
            model_name='tablesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['OPEN', 'WAITING_PAY'])), fields=('table',), name='unique_active_session_per_table'),
        ),
    ]
