# Generated by Django 5.1.15 on 2026-09-27 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0004_alter_order_delivery_type_alter_order_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='batch_round',
            field=models.PositiveIntegerField(default=1, help_text='Identifica a rodada de adição do item na comanda (1ª rodada, 2ª rodada, etc).', verbose_name='Rodada do Pedido'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Aguardando Cozinha'), ('PREPARING', 'Em Preparo'), ('READY', 'Pronto para Servir'), ('SERVED', 'Entregue na Mesa'), ('CANCELLED', 'Cancelado')], db_index=True, default='PENDING', max_length=20, verbose_name='Status do Item'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='bill_requested_at',
            field=models.DateTimeField(blank=True, help_text='Horário em que o cliente solicitou o fechamento da conta.', null=True, verbose_name='Conta Solicitada em'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_sessions', to='customers.customer', verbose_name='Cliente Titular da Mesa'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do Cliente'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='customer_phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Telefone / WhatsApp do Cliente'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='pin_code',
            field=models.CharField(blank=True, help_text='Últimos 4 dígitos do telefone do titular da mesa.', max_length=4, verbose_name='Senha / PIN da Mesa (4 dígitos)'),
        ),
    ]
