# Generated by Django 5.1.15 on 2026-09-24 23:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_store_allows_delivery_store_allows_pickup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do Cliente')),
                ('phone', models.CharField(db_index=True, help_text='Principal identificador do cliente nesta loja.', max_length=20, verbose_name='Telefone (WhatsApp)')),
                ('document', models.CharField(blank=True, help_text='Documento opcional do cliente.', max_length=20, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('notes', models.TextField(blank=True, help_text='Anotações internas sobre o cliente (ex: bom cliente, endereço de difícil acesso).', verbose_name='Observações do Estabelecimento')),
                ('orders_count', models.PositiveIntegerField(default=0, verbose_name='Quantidade de Pedidos')),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Gasto (R$)')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
                'unique_together': {('store', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('street', models.CharField(max_length=150, verbose_name='Rua / Logradouro')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('reference', models.CharField(blank=True, help_text='Ex: Ao lado da padaria, portão cinza.', max_length=150, verbose_name='Ponto de Referência')),
                ('is_default', models.BooleanField(default=False, verbose_name='Endereço Padrão')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Endereço do Cliente',
                'verbose_name_plural': 'Endereços dos Clientes',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
