services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mepedi_web
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - mepedi_media:/app/media
    networks:
      - database_net

networks:
  database_net:
    external: true

volumes:
  mepedi_media:
