# Generated by Django 5.1.15 on 2026-09-27 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0004_store_fixed_delivery_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('code', models.SlugField(help_text='Identificador único da funcionalidade (ex: orders_online, pdv, analytics).', unique=True, verbose_name='Código da Funcionalidade')),
                ('name', models.CharField(help_text='Nome legível da funcionalidade.', max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Detalhamento da funcionalidade.', verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se a funcionalidade está globalmente ativa no sistema.', verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Funcionalidade',
                'verbose_name_plural': 'Funcionalidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('gateway', models.CharField(choices=[('MERCADOPAGO', 'Mercado Pago'), ('ASAAS', 'Asaas'), ('STRIPE', 'Stripe')], default='MERCADOPAGO', max_length=30, verbose_name='Gateway')),
                ('environment', models.CharField(choices=[('SANDBOX', 'Sandbox / Testes'), ('PRODUCTION', 'Produção')], default='SANDBOX', max_length=20, verbose_name='Ambiente')),
                ('access_token', models.CharField(blank=True, help_text='Credencial secreta da API do Gateway.', max_length=255, verbose_name='Access Token')),
                ('public_key', models.CharField(blank=True, help_text='Chave pública para frontend / checkout.', max_length=255, verbose_name='Public Key')),
                ('webhook_secret', models.CharField(blank=True, help_text='Segredo de validação das assinaturas de webhook.', max_length=255, verbose_name='Webhook Secret')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Configuração de Gateway',
                'verbose_name_plural': 'Configurações de Gateway',
                'constraints': [models.UniqueConstraint(fields=('gateway', 'environment'), name='unique_gateway_per_environment')],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(help_text='Nome de exibição do plano (ex: Start, Pro, Gestão).', max_length=100, verbose_name='Nome Comercial')),
                ('slug', models.SlugField(help_text='Identificador único em URLs e integrações (ex: start, pro, gestao).', max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Apresentação dos benefícios e proposta de valor do plano.', verbose_name='Descrição Comercial')),
                ('price', models.DecimalField(decimal_places=2, help_text='Valor cobrado por ciclo de faturamento.', max_digits=10, verbose_name='Preço (R$)')),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Mensal'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=10, verbose_name='Ciclo de Faturamento')),
                ('is_active', models.BooleanField(default=True, help_text='Permite desativar um plano sem apagar o histórico de quem já contratou.', verbose_name='Ativo para Novas Contratações')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Ordenação dos planos na vitrine e checkout.', verbose_name='Ordem de Exibição')),
                ('features', models.ManyToManyField(blank=True, related_name='plans', to='subscriptions.feature', verbose_name='Funcionalidades Inclusas')),
            ],
            options={
                'verbose_name': 'Plano Comercial',
                'verbose_name_plural': 'Planos Comerciais',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('TRIAL', 'Em Período de Testes (Trial)'), ('ACTIVE', 'Ativa'), ('PAST_DUE', 'Pagamento Pendente / Atrasado'), ('SUSPENDED', 'Suspensa'), ('CANCELLED', 'Cancelada'), ('EXPIRED', 'Expirada')], db_index=True, default='TRIAL', max_length=20, verbose_name='Status da Assinatura')),
                ('trial_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Início do Trial')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fim Previsto do Trial')),
                ('trial_expired_reason', models.CharField(blank=True, choices=[('DAYS_LIMIT', 'Limite de Dias Atingido (30 dias)'), ('ORDERS_LIMIT', 'Limite de Pedidos Válidos Atingido (300 pedidos)'), ('REVENUE_LIMIT', 'Limite de Faturamento Atingido (R$ 2.000,00)')], help_text='Primeiro motivo atingido: DAYS_LIMIT, ORDERS_LIMIT ou REVENUE_LIMIT.', max_length=30, null=True, verbose_name='Motivo do Encerramento do Trial')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Ativação do Plano Pago')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='Início do Ciclo Atual')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Fim do Ciclo Atual')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Cancelamento')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='Motivo do Cancelamento')),
                ('external_customer_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID do Cliente no Gateway')),
                ('external_subscription_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID da Assinatura no Gateway')),
                ('plan', models.ForeignKey(blank=True, help_text='Nulo se a loja estiver em Trial inicial sem plano contratado.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan', verbose_name='Plano Contratado')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='stores.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('gateway', models.CharField(default='MERCADOPAGO', max_length=30, verbose_name='Gateway')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='ID da Transação no Gateway')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Cobrado (R$)')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('REFUNDED', 'Reembolsado'), ('CANCELLED', 'Cancelado')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload Bruto do Gateway')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscriptions.subscription', verbose_name='Assinatura')),
            ],
            options={
                'verbose_name': 'Histórico de Pagamento',
                'verbose_name_plural': 'Histórico de Pagamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('gateway', models.CharField(db_index=True, default='MERCADOPAGO', max_length=30, verbose_name='Gateway')),
                ('external_id', models.CharField(db_index=True, max_length=150, verbose_name='ID do Evento / Notificação')),
                ('event_type', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Tipo de Evento')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload Recebido')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSED', 'Processado'), ('IGNORED', 'Ignorado'), ('FAILED', 'Falhou')], db_index=True, default='PENDING', max_length=20, verbose_name='Status do Processamento')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
            ],
            options={
                'verbose_name': 'Evento de Webhook',
                'verbose_name_plural': 'Eventos de Webhook',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('gateway', 'external_id'), name='unique_webhook_event_per_gateway')],
            },
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['TRIAL', 'ACTIVE', 'PAST_DUE'])), fields=('store',), name='unique_active_or_trial_subscription_per_store'),
        ),
    ]
