# Generated by Django 5.1.15 on 2026-09-27 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_fixed_delivery_fee'),
        ('subscriptions', '0002_seed_saas_and_existing_stores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='Indica se o plano foi desenhado sob medida para um cliente específico.', verbose_name='Plano Personalizado'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('action', models.CharField(choices=[('SUPPORT_START', 'Início de Modo Suporte'), ('SUPPORT_END', 'Encerramento de Modo Suporte'), ('PLAN_CHANGE', 'Alteração Manual de Plano'), ('TRIAL_EXTEND', 'Extensão de Trial'), ('STORE_SUSPEND', 'Suspensão de Loja'), ('STORE_REACTIVATE', 'Reativação de Loja'), ('GATEWAY_UPDATE', 'Atualização de Gateway / Credenciais'), ('PAYMENT_MANUAL', 'Lançamento / Ajuste Manual Financeiro'), ('CUSTOM_PLAN', 'Criação / Ajuste de Plano Personalizado')], db_index=True, max_length=50, verbose_name='Ação')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detalhes da Ação')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saas_audit_logs', to='stores.store', verbose_name='Loja Afetada')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saas_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Administrador / Responsável')),
            ],
            options={
                'verbose_name': 'Registro de Auditoria',
                'verbose_name_plural': 'Trilha de Auditoria',
                'ordering': ['-created_at'],
            },
        ),
    ]
