# Generated by Django 5.1.15 on 2026-09-24 23:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(help_text='Ex: Lanchonete do Luiz', max_length=150, verbose_name='Nome do Estabelecimento')),
                ('slug', models.SlugField(help_text='Identificador da URL pública da loja (ex: lanchonete-do-luiz)', max_length=160, unique=True, verbose_name='Slug / URL Amigável')),
                ('document', models.CharField(blank=True, help_text='Documento fiscal do lojista ou empresa.', max_length=20, verbose_name='CPF ou CNPJ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone Fixo / Comercial')),
                ('whatsapp', models.CharField(help_text='Número que receberá as notificações e mensagens de pedidos.', max_length=20, verbose_name='WhatsApp para Pedidos')),
                ('description', models.TextField(blank=True, help_text='Apresentação exibida no topo do cardápio digital.', verbose_name='Descrição da Loja')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stores/logos/', verbose_name='Logotipo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='stores/banners/', verbose_name='Banner de Cabeçalho')),
                ('street', models.CharField(blank=True, max_length=150, verbose_name='Rua / Logradouro')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='Estado (UF)')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('is_active', models.BooleanField(default=True, help_text='Define se a loja pode operar no SaaS.', verbose_name='Loja Ativa na Plataforma')),
                ('is_open', models.BooleanField(default=False, help_text='Controle manual de abertura da loja.', verbose_name='Aberta para Pedidos')),
                ('is_paused', models.BooleanField(default=False, help_text='Pausa temporária de novos pedidos (ex: cozinha lotada).', verbose_name='Pedidos Pausados')),
                ('minimum_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Mínimo do Pedido')),
                ('estimated_delivery_time_min', models.PositiveIntegerField(default=30, verbose_name='Tempo Estimado Mínimo (min)')),
                ('estimated_delivery_time_max', models.PositiveIntegerField(default=60, verbose_name='Tempo Estimado Máximo (min)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_stores', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='Horário de Abertura')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Horário de Fechamento')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Fechado o Dia Todo')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Horário de Funcionamento',
                'verbose_name_plural': 'Horários de Funcionamento',
                'ordering': ['store', 'weekday'],
                'unique_together': {('store', 'weekday')},
            },
        ),
    ]
