# Generated by Django 5.1.15 on 2026-09-24 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='allows_delivery',
            field=models.BooleanField(default=True, verbose_name='Aceita Entrega / Delivery'),
        ),
        migrations.AddField(
            model_name='store',
            name='allows_pickup',
            field=models.BooleanField(default=True, verbose_name='Aceita Retirada no Local'),
        ),
        migrations.AlterField(
            model_name='businesshour',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='stores.store', verbose_name='Loja'),
        ),
    ]
