# Generated by Django 5.1.15 on 2026-09-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_allows_delivery_store_allows_pickup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='opened_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que a loja foi aberta manualmente nesta sessão.', null=True, verbose_name='Loja Aberta em'),
        ),
        migrations.AddField(
            model_name='store',
            name='preparation_time_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Tempo estimado para produção dos pedidos na cozinha.', verbose_name='Tempo Padrão de Preparo (min)'),
        ),
        migrations.AddField(
            model_name='store',
            name='thermal_receipt_message',
            field=models.TextField(blank=True, default='Agradecemos a sua preferência! Bom apetite e volte sempre!', help_text='Mensagem impressa no rodapé dos cupons para clientes.', verbose_name='Mensagem do Cupom Térmico'),
        ),
    ]
