# Generated by Django 5.1.15 on 2026-09-25 04:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_opened_at_store_preparation_time_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='fixed_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor fixo cobrado por entrega. Deixe 0.00 para entrega grátis.', max_digits=10, verbose_name='Taxa Fixa de Entrega (R$)'),
        ),
    ]
