# Generated by Django 5.1.15 on 2026-09-26 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_stockmovement_product_code_product_is_promotional_and_more'),
        ('orders', '0003_order_coupon_code_order_discount_order_operator_and_more'),
        ('stores', '0004_store_fixed_delivery_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('session_id', models.CharField(db_index=True, max_length=100, verbose_name='ID da Sessão')),
                ('event_type', models.CharField(choices=[('PAGE_VIEW', 'Visualização de Página'), ('PRODUCT_VIEW', 'Visualização de Produto'), ('ADD_TO_CART', 'Adicionado ao Carrinho'), ('CHECKOUT_STARTED', 'Início de Checkout'), ('ORDER_CREATED', 'Pedido Criado'), ('ORDER_COMPLETED', 'Pedido Concluído'), ('ORDER_CANCELLED', 'Pedido Cancelado')], db_index=True, max_length=35, verbose_name='Tipo de Evento')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='orders.order', verbose_name='Pedido Relacionado')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='catalog.product', verbose_name='Produto Relacionado')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Evento de Analytics',
                'verbose_name_plural': 'Eventos de Analytics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'event_type', 'created_at'], name='analytics_a_store_i_65d8d7_idx'), models.Index(fields=['store', 'session_id'], name='analytics_a_store_i_e225ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrackableLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(help_text='Identificação interna (ex: Bio do Instagram, Campanha Setembro).', max_length=150, verbose_name='Nome do Link')),
                ('slug_code', models.CharField(blank=True, db_index=True, help_text='Identificador amigável único por loja.', max_length=50, verbose_name='Código do Link')),
                ('destination_path', models.CharField(default='/', help_text='Caminho relativo (ex: / ou /cardapio).', max_length=255, verbose_name='Caminho de Destino')),
                ('utm_source', models.CharField(help_text='Ex: instagram, whatsapp, tiktok, facebook, google, panfleto.', max_length=100, verbose_name='Origem (utm_source)')),
                ('utm_medium', models.CharField(blank=True, default='social', help_text='Ex: bio, stories, grupo, qr, cpc.', max_length=100, verbose_name='Mídia (utm_medium)')),
                ('utm_campaign', models.CharField(blank=True, default='', help_text='Ex: lancamento, setembro, blackfriday.', max_length=150, verbose_name='Campanha (utm_campaign)')),
                ('utm_term', models.CharField(blank=True, default='', max_length=150, verbose_name='Termo (utm_term)')),
                ('utm_content', models.CharField(blank=True, default='', max_length=150, verbose_name='Conteúdo (utm_content)')),
                ('clicks_count', models.PositiveIntegerField(default=0, verbose_name='Cliques Registrados')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Link Rastreável',
                'verbose_name_plural': 'Links Rastreáveis',
                'ordering': ['-created_at'],
                'unique_together': {('store', 'slug_code')},
            },
        ),
        migrations.CreateModel(
            name='TrafficVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('session_id', models.CharField(db_index=True, max_length=100, verbose_name='ID da Sessão')),
                ('utm_source', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Origem (utm_source)')),
                ('utm_medium', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Mídia (utm_medium)')),
                ('utm_campaign', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Campanha (utm_campaign)')),
                ('utm_term', models.CharField(blank=True, max_length=150, null=True, verbose_name='Termo (utm_term)')),
                ('utm_content', models.CharField(blank=True, max_length=150, null=True, verbose_name='Conteúdo (utm_content)')),
                ('referrer', models.CharField(blank=True, max_length=500, null=True, verbose_name='Referenciador (HTTP_REFERER)')),
                ('landing_page', models.CharField(blank=True, default='/', max_length=500, verbose_name='Página de Entrada')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Visita de Tráfego',
                'verbose_name_plural': 'Visitas de Tráfego',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'created_at'], name='analytics_t_store_i_5ba2a7_idx'), models.Index(fields=['store', 'utm_source'], name='analytics_t_store_i_df3804_idx'), models.Index(fields=['store', 'utm_campaign'], name='analytics_t_store_i_d67345_idx')],
            },
        ),
    ]
