# Generated by Django 5.1.15 on 2026-09-24 23:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('description', models.TextField(blank=True, help_text='Breve descrição da categoria exibida no cardápio.', verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(default=0, help_text='Menor número aparece primeiro no cardápio.', verbose_name='Ordem de Exibição')),
                ('is_active', models.BooleanField(default=True, help_text='Categorias inativas não aparecem no cardápio público.', verbose_name='Ativa')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['order', 'name'],
                'unique_together': {('store', 'name')},
            },
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(help_text='Ex: Adicionais, Remover Ingredientes, Escolha o Molho', max_length=100, verbose_name='Nome do Grupo')),
                ('description', models.CharField(blank=True, help_text='Ex: Escolha até 3 adicionais', max_length=200, verbose_name='Instrução / Descrição')),
                ('min_options', models.PositiveIntegerField(default=0, help_text='Quantidade mínima de itens que o cliente deve escolher. 0 = Opcional.', verbose_name='Mínimo Obrigatório')),
                ('max_options', models.PositiveIntegerField(default=1, help_text='Quantidade máxima de itens que o cliente pode escolher.', verbose_name='Máximo Permitido')),
                ('is_required', models.BooleanField(default=False, help_text='Se marcado, o cliente deve escolher ao menos 1 item.', verbose_name='Seleção Obrigatória')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Grupo de Opções',
                'verbose_name_plural': 'Grupos de Opções',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(help_text='Ex: Bacon, Queijo Extra, Sem Cebola, Ao Ponto', max_length=100, verbose_name='Nome da Opção')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor adicional cobrado. Utilize 0,00 para opções gratuitas ou remoções.', max_digits=10, verbose_name='Preço Adicional (R$)')),
                ('is_available', models.BooleanField(default=True, help_text='Item disponível no momento.', verbose_name='Disponível')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('option_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.optiongroup', verbose_name='Grupo de Opções')),
            ],
            options={
                'verbose_name': 'Item de Opção',
                'verbose_name_plural': 'Itens de Opção',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do Produto')),
                ('description', models.TextField(blank=True, help_text='Ingredientes, tamanho e detalhes do produto.', verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, help_text='Valor de venda base do produto.', max_digits=10, verbose_name='Preço Base (R$)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='Foto do Produto')),
                ('is_active', models.BooleanField(default=True, help_text='Se desmarcado, fica marcado como esgotado/indisponível.', verbose_name='Disponível / Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Categoria')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='optiongroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='catalog.product', verbose_name='Produto'),
        ),
    ]
