# Generated by Django 5.1.15 on 2026-09-25 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_optiongroup_store'),
        ('orders', '0002_order_accepted_at_order_preparing_at_order_ready_at'),
        ('stores', '0004_store_fixed_delivery_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('movement_type', models.CharField(choices=[('SALE_ONLINE', 'Venda Online'), ('SALE_PDV', 'Venda PDV (Balcão)'), ('CANCEL_RETURN', 'Devolução por Cancelamento'), ('MANUAL_ADJUST', 'Ajuste Manual'), ('RESTOCK', 'Reposição de Estoque')], max_length=20, verbose_name='Tipo de Movimentação')),
                ('quantity', models.IntegerField(help_text='Valor negativo para saídas/vendas e positivo para entradas/estornos.', verbose_name='Quantidade Movimentada')),
                ('previous_stock', models.IntegerField(verbose_name='Saldo Anterior')),
                ('current_stock', models.IntegerField(verbose_name='Saldo Atual')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observações / Motivo')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, help_text='Identificador amigável e único por loja para busca rápida no PDV (ex: FAT001).', max_length=30, null=True, verbose_name='Código PDV'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_promotional',
            field=models.BooleanField(default=False, help_text='Ativa o preço promocional de venda deste produto.', verbose_name='Em Promoção'),
        ),
        migrations.AddField(
            model_name='product',
            name='promotional_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor com desconto para venda online e PDV.', max_digits=10, null=True, verbose_name='Preço Promocional (R$)'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='Saldo físico disponível para venda.', verbose_name='Quantidade em Estoque'),
        ),
        migrations.AddField(
            model_name='product',
            name='track_stock',
            field=models.BooleanField(default=False, help_text='Se ativado, as vendas online e no PDV debitam o saldo deste produto.', verbose_name='Controlar Estoque'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('code__isnull', False), models.Q(('code', ''), _negated=True)), fields=('store', 'code'), name='unique_store_product_code'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Operador / Responsável'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.order', verbose_name='Pedido Vinculado'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.product', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Loja'),
        ),
    ]
