# Generated by Django 5.1.15 on 2026-09-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_stockmovement_product_code_product_is_promotional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('SALE_ONLINE', 'Venda Online'), ('SALE_PDV', 'Venda PDV (Balcão)'), ('SALE_TABLE', 'Venda Mesa (QR Code)'), ('CANCEL_RETURN', 'Devolução por Cancelamento'), ('MANUAL_ADJUST', 'Ajuste Manual'), ('RESTOCK', 'Reposição de Estoque')], max_length=20, verbose_name='Tipo de Movimentação'),
        ),
    ]
